### ISSUE TITLE
Links open in same tab ?

### ISSUE THREAD

**Issue by sesipod** [pukmajster/bunker#1]
Hello,

So I have this downloaded and noticed that the links when clicked open in a tab / but if I click another then it overwrites the tab that was just opened.

**Comment by pukmajster** [comment]
Fixed in v1.1!

Alongside this fix I added the option "bookmarkOptions.alwaysOpenInNewTab": when set to true, bookmarks will be opened in new tabs, but when set to false, bookmarks will be opened in the current tab.
